### ISSUE TITLE
Errors in returning Real and Imaginary values

### ISSUE THREAD

**Issue by tunjid** [WuMRC/drive#17]
Hello @itkwon .

It appears there are some errors when using the getComplexOnce(double gainFactor, double &realComp, double &imagComp, double &ZVal) function.

While the overall magnitude of the impedance measured seems correct, the values of the real and imaginary components are wrong. Specifically, the size of the imaginary component is too big when compared to the LCR meter in lab. This results in phase shifts of -0.93 rads or so for regular resistors when they really should be in the order of micro-rads.

Please look into it.

@barrybelmont: AD5933 product guide: http://dkc1.digikey.com/us/en/tod/ADI/AD5933_NoAudio/AD5933_Noaudio.html

**Comment by itkwon** [comment]
We finished this issue on several months ago. We developed the solution and debugged it as TJ mentioned.
