### ISSUE TITLE
setVolPGA function has a slight error.

### ISSUE THREAD

**Issue by tunjid** [WuMRC/drive#22]
The function for setVolPGA has a slight error. The control register values for Range 2 and Range 4 are inverted. From the datasheet:

![screen shot 2015-04-07 at 10 29 28 am](https://cloud.githubusercontent.com/assets/8147224/7025338/ffe879ec-dd10-11e4-8960-58660ea3d9ec.png)

I'm going to rewrite the function to just setPGA and use setRange to set the output range. I.E, have different functions for each change to the AD5933..

**Comment by itkwon** [comment]
It is not an error. I make it based on register value (D10 & D9). However, your improvement make things easier.

**Comment by tunjid** [comment]
Oh, I see. Thanks for clearing that up.
